export const COMPANY_SEND_MSG = "COMPANY_SEND_MSG"
// export const COMPANY_LOGIN = "COMPANY_LOGIN"
// export const COMPANY_PROFILE = "COMPANY_PROFILE"
// export const GET_COMPANY_PROFILE = "GET_COMPANY_PROFILE"